#### Task 1: 6f8cd79b.json

1. Pull the json file in
2. Pull out the matrix value for the training and testing data (inputs only)
3. Convert to a numpy array
4. Run through the function to change to desired output

In [1]:
import numpy as np

In [2]:
import json
with open("C://Users/oisin/Documents/College/PTAI/Assignment 3/ARC/data/training/6f8cd79b.json") as f:
    data = json.load(f)

(data)

{'train': [{'input': [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
   'output': [[8, 8, 8], [8, 0, 8], [8, 8, 8]]},
  {'input': [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
   'output': [[8, 8, 8], [8, 0, 8], [8, 0, 8], [8, 8, 8]]},
  {'input': [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   'output': [[8, 8, 8, 8],
    [8, 0, 0, 8],
    [8, 0, 0, 8],
    [8, 0, 0, 8],
    [8, 8, 8, 8]]},
  {'input': [[0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0]],
   'output': [[8, 8, 8, 8, 8, 8],
    [8, 0, 0, 0, 0, 8],
    [8, 0, 0, 0, 0, 8],
    [8, 0, 0, 0, 0, 8],
    [8, 8, 8, 8, 8, 8]]}],
 'test': [{'input': [[0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0]],
   'output': [[8, 8, 8, 8, 8, 8],
    [8, 0, 0, 0, 0, 8],
    [8, 0, 0, 0, 0, 8],
    [8, 0, 0, 0, 0, 8],
    [8, 0, 0, 0, 0, 

$8 = \text{light blue}$ & $0 = black$

The data can be split into training and testing 

In [3]:
train = data['train']
train = [i['input'] for i in train]
train = [np.array(i) for i in train]

In [4]:
test = data['test']
test = [i['input'] for i in test]
test = np.array(test)

In [5]:
def solve_6f8cd79b(x: np.array):
    # Top row
    x[:, 0] = 8
    # Left most column
    x[0, :] = 8 
    # Bottom row
    x[-1, :] = 8 
    # Right most column
    x[:, -1] = 8
    # Pull back new matrix
    return x

In [6]:
# Testing function on training data
[solve_6f8cd79b(train[i]) for i in range(3)]

[array([[8, 8, 8],
        [8, 0, 8],
        [8, 8, 8]]),
 array([[8, 8, 8],
        [8, 0, 8],
        [8, 0, 8],
        [8, 8, 8]]),
 array([[8, 8, 8, 8],
        [8, 0, 0, 8],
        [8, 0, 0, 8],
        [8, 0, 0, 8],
        [8, 8, 8, 8]])]

In [7]:
[solve_6f8cd79b(test[i]) for i in range(1)]

[array([[8, 8, 8, 8, 8, 8],
        [8, 0, 0, 0, 0, 8],
        [8, 0, 0, 0, 0, 8],
        [8, 0, 0, 0, 0, 8],
        [8, 0, 0, 0, 0, 8],
        [8, 0, 0, 0, 0, 8],
        [8, 8, 8, 8, 8, 8]])]

Important to note that this function will also work on any numpy array passed into it of whatever n x m size filled with 0 values - awesome

In [8]:
solve_6f8cd79b(np.zeros([10,10]))

array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 0., 0., 0., 0., 0., 0., 0., 0., 8.],
       [8., 0., 0., 0., 0., 0., 0., 0., 0., 8.],
       [8., 0., 0., 0., 0., 0., 0., 0., 0., 8.],
       [8., 0., 0., 0., 0., 0., 0., 0., 0., 8.],
       [8., 0., 0., 0., 0., 0., 0., 0., 0., 8.],
       [8., 0., 0., 0., 0., 0., 0., 0., 0., 8.],
       [8., 0., 0., 0., 0., 0., 0., 0., 0., 8.],
       [8., 0., 0., 0., 0., 0., 0., 0., 0., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])